/** Builds dist/: the page, its script, and the breaker sources it shows and offers for download. */
import fs from "node:fs";
import path from "node:path";
import { build } from "esbuild";

const root = path.resolve(__dirname, "..");
const dist = path.join(root, "dist");

async function main() {
  // The code on the page is the tested files themselves, not a copy that can drift.
  const ts = fs.readFileSync(path.join(root, "src/breaker.ts"), "utf8");
  const py = fs.readFileSync(path.join(root, "src/breaker.py"), "utf8");
  fs.writeFileSync(path.join(root, "src/sources.gen.ts"),
    `// Generated by scripts/build.ts — do not edit.\nexport const SOURCE_TS = ${JSON.stringify(ts)};\nexport const SOURCE_PY = ${JSON.stringify(py)};\n`);

  fs.rmSync(dist, { recursive: true, force: true });
  fs.mkdirSync(dist, { recursive: true });
  await build({ entryPoints: [path.join(root, "src/app.ts")], bundle: true, minify: true, format: "iife", target: "es2019", outfile: path.join(dist, "app.js") });
  for (const f of ["index.html", "style.css"]) fs.copyFileSync(path.join(root, f), path.join(dist, f));
  fs.copyFileSync(path.join(root, "src/breaker.ts"), path.join(dist, "breaker.ts"));
  fs.copyFileSync(path.join(root, "src/breaker.py"), path.join(dist, "breaker.py"));
  const kb = (f: string) => `${(fs.statSync(path.join(dist, f)).size / 1024).toFixed(1)} KB`;
  console.log(`dist: app.js ${kb("app.js")}, style.css ${kb("style.css")}, index.html ${kb("index.html")}`);
}
main().catch((e) => { console.error(e); process.exit(1); });
